export const electionDefinitions = [
  {
    id: 'council-2026',
    title: 'City Council',
    description: 'Shape the next chapter of our city.',
    type: 'COUNCIL',
  },
  {
    id: 'budget-2026',
    title: 'Community Budget',
    description: 'Choose who stewards our shared resources.',
    type: 'BUDGET',
  },
  {
    id: 'community-2026',
    title: 'Neighborhood Assembly',
    description: 'Bring your neighborhood to the table.',
    type: 'COMMUNITY',
  },
] as const;
export const candidateDefinitions = [
  {
    id: 'maya',
    electionId: 'council-2026',
    fullName: 'Maya Chen',
    party: 'Green Horizon',
    ideology: 'Eco-progressive',
    color: '#64cda5',
    bio: 'An urban planner making greener, more connected neighborhoods a reality.',
    title: 'A city that works for everyone',
    content:
      'Expand accessible transit, create greener public spaces, and publish every city spending decision.',
    promises: [
      'Connect every district with clean transit',
      'Open ten neighborhood green spaces',
      'Publish a transparent city budget',
    ],
    progress: [65, 35, 100],
  },
  {
    id: 'alex',
    electionId: 'council-2026',
    fullName: 'Alex Rivera',
    party: 'Civic Forward',
    ideology: 'Social democrat',
    color: '#649af7',
    bio: 'A community organizer focused on housing, opportunity, and accountable government.',
    title: 'Opportunity on every block',
    content:
      'Build affordable homes, fund local skills training, and protect access to public services.',
    promises: [
      'Create an affordable housing pilot',
      'Launch a free skills fellowship',
      'Extend library opening hours',
    ],
    progress: [40, 80, 20],
  },
  {
    id: 'jordan',
    electionId: 'council-2026',
    fullName: 'Jordan Blake',
    party: 'Open Commons',
    ideology: 'Liberal',
    color: '#a497f3',
    bio: 'A technology educator building open institutions and a thriving local economy.',
    title: 'Open government, open opportunity',
    content:
      'Make public data accessible, support small businesses, and introduce citizen budget proposals.',
    promises: [
      'Release an open data portal',
      'Cut small business permit delays',
      'Introduce citizen budget proposals',
    ],
    progress: [100, 55, 25],
  },
  {
    id: 'samira',
    electionId: 'council-2026',
    fullName: 'Samira Okafor',
    party: 'Together Coalition',
    ideology: 'Community-first',
    color: '#efa97e',
    bio: 'A neighborhood advocate bringing everyday voices into city decision making.',
    title: 'Stronger together',
    content: 'Invest in neighborhood care, safe streets, and participatory local planning.',
    promises: [
      'Fund neighborhood care centers',
      'Improve pedestrian crossings',
      'Hold monthly citizen assemblies',
    ],
    progress: [30, 60, 100],
  },
  {
    id: 'leo',
    electionId: 'budget-2026',
    fullName: 'Leo Park',
    party: 'Civic Forward',
    ideology: 'Pragmatic',
    color: '#649af7',
    bio: 'A public finance researcher who turns complex budgets into clear choices.',
    title: 'Every unit accounted for',
    content: 'Publish simple budget reports and prioritize high-impact community investments.',
    promises: ['Publish quarterly spending reports', 'Create a citizen spending panel'],
    progress: [100, 45],
  },
  {
    id: 'ines',
    electionId: 'budget-2026',
    fullName: 'Ines Costa',
    party: 'Green Horizon',
    ideology: 'Eco-progressive',
    color: '#64cda5',
    bio: 'A sustainability coordinator directing investment toward long-term resilience.',
    title: 'Invest in tomorrow',
    content: 'Fund energy efficiency and neighborhood climate adaptation projects.',
    promises: ['Fund community solar', 'Launch a resilience grant'],
    progress: [50, 20],
  },
  {
    id: 'noah',
    electionId: 'budget-2026',
    fullName: 'Noah Ellis',
    party: 'Open Commons',
    ideology: 'Liberal',
    color: '#a497f3',
    bio: 'An entrepreneur supporting transparent, participatory public spending.',
    title: 'A budget we build together',
    content: 'Invite resident proposals and measure the outcomes of every funded project.',
    promises: ['Open resident project submissions', 'Create a project outcomes tracker'],
    progress: [80, 35],
  },
  {
    id: 'amara',
    electionId: 'community-2026',
    fullName: 'Amara Singh',
    party: 'Together Coalition',
    ideology: 'Community-first',
    color: '#efa97e',
    bio: 'A youth mentor connecting neighbors across generations.',
    title: 'A place for every neighbor',
    content: 'Create youth spaces and intergenerational community events.',
    promises: ['Open a youth makerspace', 'Launch neighbor mentoring'],
    progress: [45, 70],
  },
  {
    id: 'felix',
    electionId: 'community-2026',
    fullName: 'Felix Moreno',
    party: 'Green Horizon',
    ideology: 'Eco-progressive',
    color: '#64cda5',
    bio: 'A local gardener making public spaces welcoming and sustainable.',
    title: 'Grow our common ground',
    content: 'Create community gardens and safe walking routes.',
    promises: ['Create three community gardens', 'Map accessible walking routes'],
    progress: [65, 100],
  },
  {
    id: 'elena',
    electionId: 'community-2026',
    fullName: 'Elena Brooks',
    party: 'Civic Forward',
    ideology: 'Social democrat',
    color: '#649af7',
    bio: 'A social worker building dependable, accessible local services.',
    title: 'Care close to home',
    content: 'Expand neighborhood support and improve access to essential services.',
    promises: ['Open a community support desk', 'Introduce accessible service hours'],
    progress: [100, 55],
  },
];
