export type Language = 'en' | 'uk';

const en = {
  close: 'Close',
  miniApp: 'mini app',
  menu: 'Open app menu',
  language: 'Language',
  title: 'Dynamic Democracy',
  subtitle: 'Secure elections. Real participation.',
  subtitleSecond: 'A stronger tomorrow — together.',
  step: 'STEP',
  complete: 'COMPLETE',
  verify: 'Verify Your Identity',
  verifyCopy: 'Confirm your eligibility through a mock identity check.',
  agreement: 'Sign Civic Agreement',
  agreementCopy: 'Review the civic agreement for fair and responsible participation.',
  official: 'Official Elections',
  constitutional: 'Constitutional Legitimacy',
  blockchain: 'Blockchain-Backed Voting',
  featuresNote: 'Prototype concepts · no official authorization · blockchain is mocked',
  continue: 'Verify & Continue',
  continueReady: 'Continue to Elections',
  privacy: 'Your participation begins with informed consent.',
  demonstration: 'Demonstration only. No real identity verification or elections.',
  progress: 'Your participation progress',
  verifyIntro: 'One person. One voice.',
  mock: 'MOCK VERIFICATION',
  preview: 'BROWSER PREVIEW',
  verifyDetail:
    'This demonstration simulates eligibility. It does not verify your legal identity, citizenship, or right to vote.',
  name: 'Name for this demonstration',
  namePlaceholder: 'Enter a display name',
  nameHelp: 'Only used on this screen. Do not enter an ID number or upload documents.',
  consent: 'I understand this is a mock check and consent to continue.',
  verifyButton: 'Confirm Mock Verification',
  verifying: 'Checking eligibility…',
  nameError: 'Enter a name between 2 and 60 characters.',
  consentError: 'Please acknowledge the mock verification to continue.',
  connecting: 'Connecting to Telegram…',
  failed: 'Telegram could not connect. Reopen the Mini App from @freedomswordbot.',
  verified: 'Mock verification complete',
  verifiedDetail:
    'Your demonstration eligibility is confirmed. The next step is your civic agreement.',
  nextAgreement: 'Review Civic Agreement',
  agreementIntro: 'Participation with purpose.',
  agreementDetail:
    'Read the participation rules below. Acceptance records your consent; it is not a legal or cryptographic signature.',
  agree: 'I have read the civic agreement and accept these participation rules.',
  acceptError: 'Please read and accept the agreement to continue.',
  prerequisite: 'Complete mock verification before accepting the agreement.',
  acceptButton: 'Accept Civic Agreement',
  accepting: 'Recording acceptance…',
  accepted: 'Agreement accepted',
  acceptedDetail: 'Both steps are complete. You are ready to explore the election preview.',
  loadError: 'The agreement could not be loaded. Please try again.',
  retry: 'Try Again',
  loadingAgreement: 'Loading the civic agreement…',
  agreementLanguage: 'The recorded agreement is in English. Its original wording is shown below.',
  about: 'About FreedomSword',
  aboutTitle: 'A stronger tomorrow, together.',
  aboutCopy:
    'FreedomSword is a fictional civic participation prototype. Mock verification does not establish eligibility. The feature icons represent product concepts, not government approval or a deployed blockchain.',
  privacyTitle: 'A considered approach to privacy',
  privacyCopy:
    'In browser preview, your display name and progress stay in memory and disappear when you reload. In Telegram, the server records your mock eligibility and agreement acceptance. The operator can correlate your account and ballot. This prototype does not promise anonymity.',
  exitTitle: 'You are in browser preview',
  exitCopy:
    'In Telegram, Close returns to your chat. Here you can keep exploring the preview or return to the welcome screen.',
  keepExploring: 'Keep Exploring',
  backWelcome: 'Back to Welcome',
  dashboardEyebrow: 'YOUR CIVIC SPACE',
  dashboardTitle: 'Your voice. Our future.',
  dashboardCopy:
    'Your first two steps are complete. This is a preview of the election space to come.',
  ready: 'Ready to participate',
  identityDone: 'Mock identity check',
  agreementDone: 'Civic agreement accepted',
  electionTitle: 'Community Council',
  electionType: 'ELECTION PREVIEW',
  electionCopy:
    'A space to discover candidates, consider their commitments, and make your voice count.',
  comingSoon: 'Coming soon',
  placeholderNotice: 'Placeholder election · no candidates or voting on this screen.',
  existingElections: 'Explore the existing election demo',
  version: 'Agreement version',
  error: 'Something went wrong. Please try again.',
};

const uk: typeof en = {
  close: 'Закрити',
  miniApp: 'міні застосунок',
  menu: 'Відкрити меню',
  language: 'Мова',
  title: 'Динамічна демократія',
  subtitle: 'Надійні вибори. Справжня участь.',
  subtitleSecond: 'Сильніше майбутнє — разом.',
  step: 'КРОК',
  complete: 'ВИКОНАНО',
  verify: 'Підтвердьте особу',
  verifyCopy: 'Підтвердьте можливість участі за допомогою демонстраційної перевірки.',
  agreement: 'Прийміть громадянську угоду',
  agreementCopy: 'Ознайомтеся з угодою про чесну та відповідальну участь.',
  official: 'Офіційні вибори',
  constitutional: 'Конституційна легітимність',
  blockchain: 'Голосування на блокчейні',
  featuresNote: 'Концепції прототипу · без офіційного дозволу · імітація блокчейну',
  continue: 'Підтвердити й продовжити',
  continueReady: 'Перейти до виборів',
  privacy: 'Ваша участь починається з усвідомленої згоди.',
  demonstration: 'Лише демонстрація. Без справжньої перевірки особи чи виборів.',
  progress: 'Ваш поступ',
  verifyIntro: 'Одна людина. Один голос.',
  mock: 'ДЕМОНСТРАЦІЙНА ПЕРЕВІРКА',
  preview: 'ПЕРЕГЛЯД У БРАУЗЕРІ',
  verifyDetail:
    'Ця демонстрація імітує право на участь. Вона не перевіряє вашу особу, громадянство або право голосу.',
  name: 'Ім’я для демонстрації',
  namePlaceholder: 'Введіть ім’я',
  nameHelp: 'Лише для цього екрана. Не вводьте номер документа й не завантажуйте документи.',
  consent: 'Я розумію, що це демонстраційна перевірка, і погоджуюся продовжити.',
  verifyButton: 'Пройти демонстраційну перевірку',
  verifying: 'Перевіряємо можливість участі…',
  nameError: 'Введіть ім’я від 2 до 60 символів.',
  consentError: 'Підтвердьте розуміння демонстраційної перевірки.',
  connecting: 'Підключаємо Telegram…',
  failed: 'Не вдалося підключити Telegram. Відкрийте застосунок через @freedomswordbot.',
  verified: 'Демонстраційну перевірку завершено',
  verifiedDetail:
    'Можливість участі підтверджено для демонстрації. Наступний крок — громадянська угода.',
  nextAgreement: 'Переглянути угоду',
  agreementIntro: 'Участь із відповідальністю.',
  agreementDetail:
    'Прочитайте правила нижче. Прийняття фіксує вашу згоду; це не юридичний чи криптографічний підпис.',
  agree: 'Я прочитав(-ла) громадянську угоду та приймаю правила участі.',
  acceptError: 'Прочитайте та прийміть угоду, щоб продовжити.',
  prerequisite: 'Перед прийняттям угоди пройдіть демонстраційну перевірку.',
  acceptButton: 'Прийняти громадянську угоду',
  accepting: 'Зберігаємо згоду…',
  accepted: 'Угоду прийнято',
  acceptedDetail: 'Обидва кроки завершено. Можна перейти до перегляду виборів.',
  loadError: 'Не вдалося завантажити угоду. Спробуйте ще раз.',
  retry: 'Спробувати ще раз',
  loadingAgreement: 'Завантажуємо громадянську угоду…',
  agreementLanguage: 'Згода фіксується англійською мовою. Нижче наведено оригінальний текст.',
  about: 'Про FreedomSword',
  aboutTitle: 'Сильніше майбутнє — разом.',
  aboutCopy:
    'FreedomSword — вигаданий прототип громадянської участі. Демонстраційна перевірка не підтверджує право голосу. Іконки відображають концепції продукту, а не урядове схвалення чи справжній блокчейн.',
  privacyTitle: 'Зважений підхід до приватності',
  privacyCopy:
    'У браузері ім’я та поступ зберігаються лише в пам’яті й зникають після перезавантаження. У Telegram сервер фіксує демонстраційну перевірку та прийняття угоди. Оператор може пов’язати обліковий запис із бюлетенем. Прототип не обіцяє анонімності.',
  exitTitle: 'Ви в браузерній демонстрації',
  exitCopy:
    'У Telegram кнопка «Закрити» повертає до чату. Тут можна продовжити перегляд або повернутися до привітання.',
  keepExploring: 'Продовжити перегляд',
  backWelcome: 'До привітання',
  dashboardEyebrow: 'ВАШ ГРОМАДЯНСЬКИЙ ПРОСТІР',
  dashboardTitle: 'Ваш голос. Наше майбутнє.',
  dashboardCopy:
    'Перші два кроки завершено. Це попередній перегляд майбутнього виборчого простору.',
  ready: 'Готовність до участі',
  identityDone: 'Демонстраційна перевірка',
  agreementDone: 'Громадянську угоду прийнято',
  electionTitle: 'Громадська рада',
  electionType: 'ПЕРЕГЛЯД ВИБОРІВ',
  electionCopy: 'Простір для знайомства з кандидатами, їхніми зобов’язаннями та вашого голосу.',
  comingSoon: 'Незабаром',
  placeholderNotice: 'Макет виборів · на цьому екрані немає кандидатів чи голосування.',
  existingElections: 'Переглянути наявну демонстрацію виборів',
  version: 'Версія угоди',
  error: 'Сталася помилка. Спробуйте ще раз.',
};

export const copy = { en, uk };
export type WelcomeCopy = typeof en;
